### ISSUE TITLE
Dockerize the project

### ISSUE THREAD

**Issue by enoriega** [enoriega/frailty_graph_viz#17]
Create a docker image for development and deployment of the project

**Comment by rahatzamancse** [comment]
@enoriega 

Please recreate the pickle file in the dockerize (0ed7d5abc822f91d565bfa53bace3dbca29dd618) branch and share it. Then I can proceed with the rest of the dockerization process.

**Comment by enoriega** [comment]
Hopefully this will be the last time we have to do this. Once we migrate to a graph database

**Comment by rahatzamancse** [comment]
Seems that my problem with dockerizing the backend still exists even after rebuilding the pickle with the needed context. The log is given below. Let me know if you can help on this. Or we can wait until we move to neo4j and then work on this issue.

```text
Loading data ...
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 437, in main
    run(app, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/code/backend/./start.py", line 11, in <module>
    from viz_api import api_router as viz_api_router
  File "/code/backend/./viz_api.py", line 205, in <module>
    def interaction(source, destination, bidirectional: bool, graph: MultiDiGraph = get_graph(),
  File "/code/backend/./dependencies.py", line 109, in get_graph
    graph, _ = read_graph_and_significance()
  File "/code/backend/./dependencies.py", line 90, in read_graph_and_significance
    data = pickle.load(f)
```

**Comment by enoriega** [comment]
I will fix this soon.

**Comment by rahatzamancse** [comment]
@enoriega, I need your help. For the last three days, I am kind of stuck in a problem. If I run both front-enc and backend dockers separately, their is no problem and everything works fine. But when I run then from docker-compose, there seems to be CORS error from the browser. 

![image](https://user-images.githubusercontent.com/22135181/162579732-c28eecb1-98d6-4059-9f0f-23b6f1d39317.png)

You can regenerate the error from the dockerize branch easily. Just do `docker-compose up` and open the frontend in `localhost:3000` (backend can be accessed in `localhost:1601`.

**Comment by enoriega** [comment]
@rahatzamancse I will take a look.
Let's put this on hold for now and please focus on the viz fixes from last week's meeting with the med school folks.
Thanks!

**Comment by rahatzamancse** [comment]
@enoriega, #38 fixes this issue. We have another branch named dockerize. I propose we delete that one as #38 supersedes that one.
